version: '3.8'
services:
  db:
    # ...
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    # ...

  redis:
    # ...

  celery_worker:
    # ...
    command: celery -A something.celery worker --loglevel=debug --concurrency=4
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  django_app:
    # ...
    command: gunicorn something.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django_app

volumes:
  local_pgdata:
