# Generated by Django 4.2.1 on 2023-06-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_item_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
