# Generated by Django 4.0.6 on 2023-02-25 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ManyToManyField(blank=True, to='realtime.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
