# Generated by Django 4.0.6 on 2023-02-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='server',
            field=models.CharField(blank=True, choices=[('app_notification', 'app_notification'), ('chat_notification', 'chat_notification')], max_length=100, null=True),
        ),
    ]
