# Generated by Django 4.0.6 on 2023-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
