# Generated by Django 4.0.6 on 2023-03-01 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtime', '0007_notification_object_text_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSocketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_id_in_server', models.IntegerField(blank=True, null=True)),
                ('server_name', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
