# Generated by Django 4.0.6 on 2023-02-06 10:00

import app.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_postmedia_media_postmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=app.models.get_upload_path, validators=[app.models.file_size]),
        ),
    ]
