# Generated by Django 4.0.6 on 2022-11-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='unfriend',
            field=models.BooleanField(default=False),
        ),
    ]
