# Generated by Django 4.0.6 on 2022-11-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_relationship_unfriend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='unfriend',
        ),
    ]
