# Generated by Django 4.0.6 on 2023-02-06 10:00

from django.db import migrations, models
import user.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_block_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='time_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='poster_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=user.models.get_upload_path, validators=[user.models.file_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=user.models.get_upload_path, validators=[user.models.file_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
