# Generated by Django 4.0.6 on 2023-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
